#### Bước 1: Khai báo các thư viện cần thiết

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sys

from sklearn import neighbors, datasets

#### Tiếp theo, Bước 2: Load dữ liệu và hiển thị dữ liệu mẫu (iris là dữ liệu có sẵn trong sklearn)

In [2]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
print('Số lớp: ', len(np.unique(iris_y)))
print('Số lượng điểm dữ liệu: ', len(iris_y))


X0 = iris_X[iris_y == 0,:]
print('\nVí dụ từ lớp thứ 0:\n', X0[:5,:])

X1 = iris_X[iris_y == 1,:]
print('\nVí dụ từ lớp thứ 1:\n', X1[:5,:])

X2 = iris_X[iris_y == 2,:]
print('\nVí dụ từ lớp thứ 2:\n', X2[:5,:])


Số lớp:  3
Số lượng điểm dữ liệu:  150

Ví dụ từ lớp thứ 0:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Ví dụ từ lớp thứ 1:
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]

Ví dụ từ lớp thứ 2:
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


Nếu nhìn vào vài dữ liệu mẫu, chúng ta thấy rằng hai cột cuối mang khá nhiều thông tin giúp chúng ta có thể  phân biệt được chúng. Chúng ta dự đoán rằng kết quả classification cho cơ sở dữ liệu này sẽ tương đối cao.

#### Bước 3: Tách training và test sets
Giả sử chúng ta muốn dùng 50 điểm dữ liệu cho test set, 100 điểm còn lại cho training set. Scikit-learn có một hàm số cho phép chúng ta ngẫu nhiên lựa chọn các điểm này, như sau:

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
     iris_X, iris_y, test_size=50)

print("Kết quả nhận được: ")
print("Training size: %d" %len(y_train))
print("Test size    : %d" %len(y_test))

Kết quả nhận được: 
Training size: 100
Test size    : 50


#### Bước 4: KNN dự đoán
Sau đây, tôi xét trường hợp đơn giản \\(K=1\\), tức là với mỗi điểm test data, ta chỉ xét 1 điểm train gần nhất và lấy label của điểm đó để dự đoán cho điểm test này. 
(Khi cho 1 điểm bất kỳ, để biết được n điểm gần nhất thì thuật toán này tính hết khoảng cách từ điểm data test này tới tất cả các điểm trong training data sau đó lấy ra 10 điểm có khoảng cách gần nhất)

In [4]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 1, p = 2)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("Kết quả nhận đươc: ")
print("Print results for first 20 test data points:")
print("Predicted labels: ", y_pred[20:40])
print("Ground truth    : ", y_test[20:40])

Kết quả nhận đươc: 
Print results for first 20 test data points:
Predicted labels:  [0 1 2 2 2 2 1 1 0 0 0 2 0 2 1 2 0 1 1 0]
Ground truth    :  [0 1 2 2 2 2 1 1 0 0 0 2 0 2 1 2 0 1 1 0]


Kết quả cho thấy kết quả dự đoán gần giống với label thật của test data, chỉ có 2 điểm trong số 20 điểm được hiển thị có kết quả sai lệch. 

#### Bước 5: Đánh giá
Để đánh giá độ chính xác của thuật toán KNN, chúng ta xem xem có bao nhiêu điểm trong test data được dự đoán đúng. Số lượng này chia cho tổng số lượng trong tập test data sẽ ra độ chính xác. Scikit-learn cung cấp hàm số [`accuracy_score`](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html) để thực hiện công việc này.

In [5]:
from sklearn.metrics import accuracy_score
print("Accuracy of 1NN: %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Accuracy of 1NN: 96.00 %


Với K = 1 đã cho kết quả là 94%. Nhận thấy rằng nếu chỉ xét 1 điểm gàn nhất có thể dẫn đến kết quả sai nếu điểm đó là nhiễu. Vậy nêu ta thử xét với K=9 thì kết quả sẽ như thế nào?

Kết quả nhận được:

In [6]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 9, p = 2)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("Accuracy of 9NN: %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Accuracy of 9NN: 94.00 %


Như vậy chúng ta đã giải quyết được bài toán đặt ra với kết quả thu được gần như hoàn hảo.

Trong kỹ thuật major voting bên trên, mỗi trong 9 điểm gần nhất được coi là có vai trò như nhau và giá trị lá phiếu của mỗi điểm này là như nhau. Xét trên thực tế đều này là không đúng, vì rõ ràng những điểm gần hơn sẽ phải có trọng số cao hơn. Vậy nên ta sẽ đánh trọng số kahsc nhau cho 9 điểm đang xét nhưng phả thỏa mãn điều kiện điểm gần test data thì phải có trọng số càng cao.

Scikit-learn giúp chúng ta đơn giản hóa việc này bằng cách gán gía trị weights = 'distance'. (Giá trị mặc định của weights là 'uniform', tương ứng với việc coi tất cả các điểm lân cận có giá trị như nhau như ở trên).

In [9]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 9, p = 2, weights = 'distance')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print ("Accuracy of 9NN (1/distance weights): %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Accuracy of 9NN (1/distance weights): 94.00 %


Kết quả nhận được không thay đổi

#### Kết luận:
- Hạn chế của thuật toán KNN:
+ Thuật toán phụ thuộc nhiều vào hệ số K
+ Kết quả đưa ra có sự thay đổi (vì c